packages:
  - apps/*
  - orion-apps/*
  - packages/*
  - kreator-apps/*
  - kreator-packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
